/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dadostratados.FornecedorDadosTratados;
import dadostratados.ProdutoDadosTratados;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Fornecedor;
import modelos.Produto;
import modelos.Utilitarios;

/**
 *
 * @author rober
 */
public class FrmProdutos extends javax.swing.JFrame {

    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
        initComponents();
    }
    
    //Listando todos os produtos na JTable do Formulário de Produtos 'FrmProdutos'.
    public void listarTodosNaJTable(){
        List<Produto> lista = new ArrayList<>();
        ProdutoDadosTratados pdt = new ProdutoDadosTratados();
        lista = pdt.listarTodos();
        
        DefaultTableModel dados = (DefaultTableModel) tblProdutos.getModel();
        
        //limpa o tipo 'DefaultTableModel'.
        dados.setNumRows(0);         
        
        for(Produto p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtdEstoque(),
                p.getFornecedor().getNome()
 
            });
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelComGuias = new javax.swing.JTabbedPane();
        painelDeDados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtestoque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbFornecedores = new javax.swing.JComboBox();
        btnPesquisarDescricaoGuia1 = new javax.swing.JButton();
        painelComTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtDescricaoGuia2 = new javax.swing.JTextField();
        btnPesquisarDescricaoGuia2 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        painelDeDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelDeDadosMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        txtdescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Preço:");

        txtpreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qtd. em Estoque");

        txtestoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Fornecedor:");

        cbFornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbFornecedores.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFornecedoresAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFornecedoresMouseClicked(evt);
            }
        });

        btnPesquisarDescricaoGuia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarDescricaoGuia1.setText("Pesquisar");
        btnPesquisarDescricaoGuia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDescricaoGuia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeDadosLayout = new javax.swing.GroupLayout(painelDeDados);
        painelDeDados.setLayout(painelDeDadosLayout);
        painelDeDadosLayout.setHorizontalGroup(
            painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeDadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDeDadosLayout.createSequentialGroup()
                        .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarDescricaoGuia1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDeDadosLayout.createSequentialGroup()
                        .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        painelDeDadosLayout.setVerticalGroup(
            painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeDadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDescricaoGuia1))
                .addGap(18, 18, 18)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        painelComGuias.addTab("Dados do Produto", painelDeDados);

        tblProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Qtd. Estoque", "Fornecedor"
            }
        ));
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descrição");

        txtDescricaoGuia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPesquisarDescricaoGuia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarDescricaoGuia2.setText("Pesquisar");
        btnPesquisarDescricaoGuia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDescricaoGuia2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelComTabelaLayout = new javax.swing.GroupLayout(painelComTabela);
        painelComTabela.setLayout(painelComTabelaLayout);
        painelComTabelaLayout.setHorizontalGroup(
            painelComTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComTabelaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelComTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(painelComTabelaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescricaoGuia2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarDescricaoGuia2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 327, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelComTabelaLayout.setVerticalGroup(
            painelComTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComTabelaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(painelComTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescricaoGuia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDescricaoGuia2))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelComGuias.addTab("Consulta de Produtos", painelComTabela);

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovo.setText("LIMPAR");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("SALVAR NOVO");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelComGuias)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnSalvar)
                .addGap(69, 69, 69)
                .addComponent(btnAtualizar)
                .addGap(76, 76, 76)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtualizar, btnExcluir, btnNovo, btnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelComGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtualizar, btnExcluir, btnNovo, btnSalvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // lista de todos os registros da tabela 'tb_fornecedores'.
        listarTodosNaJTable();
        
    }//GEN-LAST:event_formWindowActivated

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        new Utilitarios().LimpaTela(painelDeDados);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cbFornecedoresAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFornecedoresAncestorAdded
        // Esse evento sempre vai executar quando o componente for ativado. 
        FornecedorDadosTratados dados = new FornecedorDadosTratados();
        List<Fornecedor> lista = dados.listarTodos();
        //lista = dados.listarTodos();
        
        cbFornecedores.removeAllItems();
        for(Fornecedor f : lista){
            cbFornecedores.addItem(f);
        }
    }//GEN-LAST:event_cbFornecedoresAncestorAdded

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Produto objP = new Produto();
        objP.setDescricao(txtdescricao.getText());
        objP.setPreco(Double.parseDouble(txtpreco.getText()));
        objP.setQtdEstoque(Integer.parseInt(txtestoque.getText()));              
        
        //Criar um objeto Fornecedor que receba o objeto do JComboBox
        Fornecedor objF = new Fornecedor();
        objF = (Fornecedor) cbFornecedores.getSelectedItem();
        objP.setFornecedor(objF);
        
        ProdutoDadosTratados dados = new ProdutoDadosTratados();
        dados.cadastrar(objP);
        
        new Utilitarios().LimpaTela(painelDeDados);
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarDescricaoGuia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDescricaoGuia1ActionPerformed
        // TODO add your handling code here:
        String descricao = txtdescricao.getText();
               
        ProdutoDadosTratados dadosP = new ProdutoDadosTratados();
        Produto objP = new Produto();
        
        objP = dadosP.pesquisarPorDescricao(descricao);
        
        cbFornecedores.removeAllItems();
        
        if(objP.getDescricao() != null){
            
            //Os dados do Produto buscado serão setados nos campos do formulário.
            txtcodigo.setText(String.valueOf(objP.getId()));
            txtdescricao.setText(objP.getDescricao());
            txtpreco.setText(String.valueOf(objP.getPreco()));
            txtestoque.setText(String.valueOf(objP.getQtdEstoque()));
            
            //cbFornecedores.setSelectedItem(obj.getFornecedor());
            Fornecedor objF = new Fornecedor();
            FornecedorDadosTratados dadosF = new FornecedorDadosTratados();
            
            objF = dadosF.pesquisarPorNome(objP.getFornecedor().getNome());
            
            cbFornecedores.getModel().setSelectedItem(objF);
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Produto não encontrado!");
        }
        
        
    }//GEN-LAST:event_btnPesquisarDescricaoGuia1ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        
        Produto objP = new Produto();
        
        objP.setId(Integer.parseInt(txtcodigo.getText()));
        objP.setPreco(Double.parseDouble(txtpreco.getText()));
        objP.setDescricao(txtdescricao.getText());
        objP.setQtdEstoque(Integer.parseInt(txtestoque.getText()));
        objP.setFornecedor((Fornecedor) cbFornecedores.getSelectedItem());
               
        ProdutoDadosTratados dados = new ProdutoDadosTratados();
        dados.atualizar(objP);
        new Utilitarios().LimpaTela(painelDeDados);
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarDescricaoGuia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDescricaoGuia2ActionPerformed
        // TODO add your handling code here:
        
        String descricao = "%"+txtDescricaoGuia2.getText()+"%";
        List<Produto> lista = new ArrayList<>();
        ProdutoDadosTratados dadostd = new ProdutoDadosTratados();
                        
        
        lista = dadostd.listarPorDescricao(descricao);
        
        DefaultTableModel dados = (DefaultTableModel) tblProdutos.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtdEstoque(),
                p.getFornecedor().getNome()

            });
        }
        
        
    }//GEN-LAST:event_btnPesquisarDescricaoGuia2ActionPerformed

    private void painelDeDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDeDadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_painelDeDadosMouseClicked

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        //pega os dados
        painelComGuias.setSelectedIndex(0);
        
        txtcodigo.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(),0).toString());
        txtdescricao.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(),1).toString());
        txtpreco.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(),2).toString());
        txtestoque.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(),3).toString());
        
        /*Dois objetos foram criados: um objeto 'Fornecedor' e um obj 'FornecedorDadosTratados'.
        obj Fornecedor: irá armazenar o resultado da busca pelo nome do fornecedor.
        obj FornecedorDadosTratados: criado para que método responsável pela busca seja implementado.*/
        Fornecedor objF = new Fornecedor();
        FornecedorDadosTratados dados = new FornecedorDadosTratados();
        String nome = tblProdutos.getValueAt(tblProdutos.getSelectedRow(),4).toString();
        objF = dados.pesquisarPorNome(nome);                
        
        cbFornecedores.removeAllItems();
        cbFornecedores.getModel().setSelectedItem(objF);
        
        
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        ProdutoDadosTratados dados = new ProdutoDadosTratados();
        dados.excluir(Integer.parseInt(txtcodigo.getText()));
        new Utilitarios().LimpaTela(painelDeDados);
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFornecedoresMouseClicked
        // TODO add your handling code here:
        FornecedorDadosTratados dadosF = new FornecedorDadosTratados();
        List<Fornecedor> listaF = dadosF.listarTodos();
        cbFornecedores.removeAllItems();
        
        for(Fornecedor f : listaF){
            cbFornecedores.addItem(f);
        }
    }//GEN-LAST:event_cbFornecedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarDescricaoGuia1;
    private javax.swing.JButton btnPesquisarDescricaoGuia2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane painelComGuias;
    private javax.swing.JPanel painelComTabela;
    private javax.swing.JPanel painelDeDados;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtDescricaoGuia2;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtestoque;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
